#!/bin/bash

CP=$HOME/lib/commons-cli-1.2
HP=$HOME/lib/htmlunit-2.9/lib

CLASSPATH=.
CLASSPATH=$CLASSPATH:$CP/commons-cli-1.2.jar

CLASSPATH=$CLASSPATH:\
$HP/commons-codec-1.4.jar:\
$HP/commons-collections-3.2.1.jar:\
$HP/commons-io-2.0.1.jar:\
$HP/commons-lang-2.6.jar:\
$HP/commons-logging-1.1.1.jar:\
$HP/cssparser-0.9.5.jar:\
$HP/htmlunit-2.9.jar:\
$HP/htmlunit-core-js-2.9.jar:\
$HP/httpclient-4.1.2.jar:\
$HP/httpcore-4.1.2.jar:\
$HP/httpmime-4.1.2.jar:\
$HP/nekohtml-1.9.15.jar:\
$HP/sac-1.3.jar:\
$HP/serializer-2.7.1.jar:\
$HP/xalan-2.7.1.jar:\
$HP/xercesImpl-2.9.1.jar:\
$HP/xml-apis-1.3.04.jar

export CLASSPATH
