# Generated by Django 2.2.7 on 2019-12-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('wcag20', '0001_initial'),
        ('ruleCategories', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status')),
                ('manual_check_status', models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('title', models.CharField(default='No title', max_length=1024, verbose_name='Title')),
                ('num_total_pages', models.IntegerField(default=0)),
                ('num_total_reports', models.IntegerField(default=0)),
                ('ws_reports', models.ManyToManyField(blank=True, default=None, to='reports.WebsiteReport')),
            ],
            options={
                'verbose_name': 'Website Report Group',
                'verbose_name_plural': 'Website Report Groups',
            },
        ),
        migrations.CreateModel(
            name='WebsiteRuleScopeResultGroup',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status')),
                ('manual_check_status', models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='none', editable=False, max_length=16)),
                ('rule_scope', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.RuleScope')),
                ('wsr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rs_result_groups', to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Website Rule Scope Result Group',
                'verbose_name_plural': 'Website Rule Scope Result Groups',
                'ordering': ['-rule_scope'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteRuleResultGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status')),
                ('manual_check_status', models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status')),
                ('slug', models.SlugField(default='none', editable=False, max_length=16)),
                ('pages_violation', models.IntegerField(default=0)),
                ('pages_warning', models.IntegerField(default=0)),
                ('pages_manual_check', models.IntegerField(default=0)),
                ('pages_passed', models.IntegerField(default=0)),
                ('pages_na', models.IntegerField(default=0)),
                ('pages_with_hidden_content', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.Rule')),
                ('wsr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rule_result_groups', to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteRuleCategoryResultGroup',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status')),
                ('manual_check_status', models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='none', editable=False, max_length=16)),
                ('rule_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ruleCategories.RuleCategory')),
                ('wsr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rc_result_groups', to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Website Rule Category Result Group',
                'verbose_name_plural': 'Website Rule Category Result Groups',
                'ordering': ['rule_category'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteGuidelineResultGroup',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status')),
                ('manual_check_status', models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='none', editable=False, max_length=16)),
                ('guideline', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wcag20.Guideline')),
                ('wsr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_gl_result_groups', to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Website Guideline Result Grouo',
                'verbose_name_plural': 'Website Guideline Result Groups',
                'ordering': ['guideline'],
            },
        ),
    ]
