# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wcag20', '0001_initial'),
        ('rules', '0001_initial'),
        ('websiteResultGroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteRuleScopeResultGroup',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Status')),
                ('manual_check_status', models.CharField(choices=[(b'NC', b'Not Checked'), (b'NA', b'Not Applicable'), (b'P', b'Passed'), (b'F', b'Fail')], default=b'NC', max_length=2, verbose_name=b'Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=b'none', editable=False, max_length=16)),
                ('rule_scope', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='rules.RuleScope')),
            ],
            options={
                'ordering': ['-rule_scope'],
                'verbose_name': 'Website Rule Scope Result Group',
                'verbose_name_plural': 'Website Rule Scope Result Groups',
            },
        ),
        migrations.AlterModelOptions(
            name='websiteguidelineresultgroup',
            options={'ordering': ['guideline'], 'verbose_name': 'Website Guideline Result Grouo', 'verbose_name_plural': 'Website Guideline Result Groups'},
        ),
        migrations.RemoveField(
            model_name='websiteguidelineresultgroup',
            name='rule_scope',
        ),
        migrations.AddField(
            model_name='websiteguidelineresultgroup',
            name='guideline',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='wcag20.Guideline'),
        ),
        migrations.AddField(
            model_name='websitereportgroup',
            name='title',
            field=models.CharField(default=b'No title', max_length=1024, verbose_name=b'Title'),
        ),
        migrations.AlterField(
            model_name='websiteguidelineresultgroup',
            name='wsr_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_gl_result_groups', to='websiteResultGroups.WebsiteReportGroup'),
        ),
        migrations.AlterField(
            model_name='websitereportgroup',
            name='ws_reports',
            field=models.ManyToManyField(blank=True, default=None, to='reports.WebsiteReport'),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresultgroup',
            name='rule_category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ruleCategories.RuleCategory'),
        ),
        migrations.AlterField(
            model_name='websiteruleresultgroup',
            name='rule',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='rules.Rule'),
        ),
        migrations.AddField(
            model_name='websiterulescoperesultgroup',
            name='wsr_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rs_result_groups', to='websiteResultGroups.WebsiteReportGroup'),
        ),
    ]
