# Generated by Django 2.2.7 on 2019-12-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='no account type title', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('self_registration', models.BooleanField(default=False)),
                ('shibboleth', models.BooleanField(default=False)),
                ('self_hosted', models.BooleanField(default=False)),
                ('sponsor', models.BooleanField(default=False)),
                ('max_archive', models.IntegerField(default=10)),
                ('max_permanent', models.IntegerField(default=5)),
                ('max_depth', models.IntegerField(default=2)),
                ('max_pages', models.IntegerField(default=25)),
                ('advanced', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('next_account_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_account_type', to='accounts.AccountType')),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
                'ordering': ['type_id'],
            },
        ),
    ]
