# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttype_next_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='title',
            field=models.CharField(default='no account type title', max_length=64),
        ),
    ]
