# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('ruleCategories', '0001_initial'),
        ('rules', '0001_initial'),
        ('wcag20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteGuidelineResult',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Status')),
                ('manual_check_status', models.CharField(choices=[(b'NC', b'Not Checked'), (b'NA', b'Not Applicable'), (b'P', b'Passed'), (b'F', b'Fail')], default=b'NC', max_length=2, verbose_name=b'Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default=b'none', editable=False, max_length=16)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcag20.Guideline')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_gl_results', to='reports.WebsiteReport')),
            ],
            options={
                'ordering': ['guideline'],
                'verbose_name': 'Website Guideline Result',
                'verbose_name_plural': 'Website Guideline Results',
            },
        ),
        migrations.CreateModel(
            name='WebsiteRuleCategoryResult',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Status')),
                ('manual_check_status', models.CharField(choices=[(b'NC', b'Not Checked'), (b'NA', b'Not Applicable'), (b'P', b'Passed'), (b'F', b'Fail')], default=b'NC', max_length=2, verbose_name=b'Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default=b'none', editable=False, max_length=16)),
                ('rule_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruleCategories.RuleCategory')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rc_results', to='reports.WebsiteReport')),
            ],
            options={
                'ordering': ['rule_category'],
                'verbose_name': 'Website Rule Category Result',
                'verbose_name_plural': 'Website Rule Category Results',
            },
        ),
        migrations.CreateModel(
            name='WebsiteRuleResult',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Status')),
                ('manual_check_status', models.CharField(choices=[(b'NC', b'Not Checked'), (b'NA', b'Not Applicable'), (b'P', b'Passed'), (b'F', b'Fail')], default=b'NC', max_length=2, verbose_name=b'Manual Check Status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default=b'none', editable=False, max_length=16)),
                ('rule_required', models.BooleanField(default=False)),
                ('rule_number', models.IntegerField(default=-1)),
                ('pages_violation', models.IntegerField(default=0)),
                ('pages_warning', models.IntegerField(default=0)),
                ('pages_manual_check', models.IntegerField(default=0)),
                ('pages_passed', models.IntegerField(default=0)),
                ('pages_na', models.IntegerField(default=0)),
                ('elements_violation', models.IntegerField(default=0)),
                ('elements_warning', models.IntegerField(default=0)),
                ('elements_mc_identified', models.IntegerField(default=0)),
                ('elements_mc_passed', models.IntegerField(default=0)),
                ('elements_mc_failed', models.IntegerField(default=0)),
                ('elements_mc_na', models.IntegerField(default=0)),
                ('elements_passed', models.IntegerField(default=0)),
                ('elements_hidden', models.IntegerField(default=0)),
                ('pages_with_hidden_content', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Rule')),
                ('ws_gl_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rule_results', to='websiteResults.WebsiteGuidelineResult')),
                ('ws_rc_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rule_results', to='websiteResults.WebsiteRuleCategoryResult')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rule_results', to='reports.WebsiteReport')),
            ],
            options={
                'ordering': ['-pages_violation', '-pages_warning', '-pages_manual_check', '-pages_passed', '-pages_with_hidden_content', '-rule__scope'],
                'verbose_name': 'Website Rule Result',
                'verbose_name_plural': 'Website Rule Results',
            },
        ),
        migrations.CreateModel(
            name='WebsiteRuleScopeResult',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'C', b'Complete')], default=b'U', max_length=2, verbose_name=b'Implementation Status')),
                ('manual_check_status', models.CharField(choices=[(b'NC', b'Not Checked'), (b'NA', b'Not Applicable'), (b'P', b'Passed'), (b'F', b'Fail')], default=b'NC', max_length=2, verbose_name=b'Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default=b'none', editable=False, max_length=16)),
                ('rule_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.RuleScope')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rs_results', to='reports.WebsiteReport')),
            ],
            options={
                'ordering': ['-rule_scope'],
                'verbose_name': 'Website Rule Scope Result',
                'verbose_name_plural': 'Website Rule Scope Results',
            },
        ),
        migrations.AddField(
            model_name='websiteruleresult',
            name='ws_rs_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_rule_results', to='websiteResults.WebsiteRuleScopeResult'),
        ),
    ]
