# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteguidelineresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='websiteguidelineresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='websiteguidelineresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='websiteguidelineresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='websiterulecategoryresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='websiteruleresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='websiteruleresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='websiteruleresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='websiteruleresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='websiterulescoperesult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='websiterulescoperesult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='websiterulescoperesult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='websiterulescoperesult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=16),
        ),
    ]
