# Generated by Django 2.2.7 on 2019-12-18 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rulesets', '0001_initial'),
        ('websiteResultGroups', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats All',
                'verbose_name_plural': 'Stats All',
            },
        ),
        migrations.CreateModel(
            name='StatsYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2016)),
                ('stats_all', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='stats.StatsAll')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats Year',
                'verbose_name_plural': 'Stats Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='StatsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats User',
                'verbose_name_plural': 'Stats User',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='StatsRuleset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruleset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='rulesets.Ruleset')),
                ('stats_all', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rulesets', to='stats.StatsAll')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats Ruleset',
                'verbose_name_plural': 'Stats Rulesets',
                'ordering': ['ruleset'],
            },
        ),
        migrations.CreateModel(
            name='StatsRegisteredUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_stats', models.ManyToManyField(blank=True, default=None, related_name='stats_registered_users', to='stats.StatsUser')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats Registered Users',
                'verbose_name_plural': 'Stats Registered Users',
            },
        ),
        migrations.CreateModel(
            name='StatsMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=1)),
                ('stats_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='stats.StatsYear')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats Month',
                'verbose_name_plural': 'Stats Months',
                'ordering': ['-stats_year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='StatsDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('day', models.IntegerField(default=1)),
                ('stats_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='stats.StatsMonth')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats Day',
                'verbose_name_plural': 'Stats Day',
                'ordering': ['-stats_month', '-day'],
            },
        ),
    ]
