# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteResultGroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsMonth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StatsYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2016)),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
        ),
        migrations.AddField(
            model_name='statsmonth',
            name='stats_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.StatsYear'),
        ),
        migrations.AddField(
            model_name='statsmonth',
            name='ws_report_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup'),
        ),
        migrations.AddField(
            model_name='statsday',
            name='stats_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.StatsMonth'),
        ),
        migrations.AddField(
            model_name='statsday',
            name='ws_report_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup'),
        ),
    ]
