# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResultGroups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'Stats User',
                'verbose_name_plural': 'Stats User',
            },
        ),
        migrations.AlterModelOptions(
            name='statsday',
            options={'ordering': ['-stats_month', '-date'], 'verbose_name': 'Stats Day', 'verbose_name_plural': 'Stats Day'},
        ),
        migrations.AlterModelOptions(
            name='statsmonth',
            options={'ordering': ['-stats_year', '-month'], 'verbose_name': 'Stats Month', 'verbose_name_plural': 'Stats Months'},
        ),
        migrations.AlterModelOptions(
            name='statsyear',
            options={'ordering': ['-year'], 'verbose_name': 'Stats Year', 'verbose_name_plural': 'Stats Years'},
        ),
    ]
