# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20160220_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
