# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResultGroups', '0001_initial'),
        ('stats', '0002_auto_20160302_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsRegisteredUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_stats', models.ManyToManyField(blank=True, default=None, related_name='stats_registered_users', to='stats.StatsUser')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
            options={
                'verbose_name': 'Stats Registered Users',
                'verbose_name_plural': 'Stats Registered Users',
            },
        ),
        migrations.RemoveField(
            model_name='statsusers',
            name='user_stats',
        ),
        migrations.RemoveField(
            model_name='statsusers',
            name='ws_report_group',
        ),
        migrations.DeleteModel(
            name='StatsUsers',
        ),
    ]
