# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcag20', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='number',
            field=models.CharField(default='none', max_length=8),
        ),
        migrations.AlterField(
            model_name='successcriterion',
            name='level',
            field=models.CharField(choices=[('1', 'Level A'), ('2', 'Level AA'), ('3', 'Level AAA')], max_length=2),
        ),
        migrations.AlterField(
            model_name='successcriterion',
            name='number',
            field=models.CharField(default='none', max_length=8),
        ),
    ]
