#!/usr/bin/env bash

scripts="test/oaa_scripts.txt"
output="tmp"

if [ -d $output ]
then
    echo Removing $output directory...
    rm -rf $output
fi

echo Running java org.ainspector.util.AInspector --scripts $scripts --output $output $@

. org/ainspector/util/classpath
java org.ainspector.util.AInspector --scripts $scripts --output $output $@
