# Generated by Django 2.2.7 on 2019-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_date', models.DateTimeField(editable=False)),
                ('ruleset_id', models.CharField(max_length=64)),
                ('version', models.CharField(default='unknown', max_length=16, verbose_name='Ruleset Version')),
                ('slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=128, verbose_name='Ruleset Title')),
                ('title_html', models.CharField(default='', max_length=512)),
                ('title_text', models.CharField(default='', max_length=128)),
                ('tooltip', models.CharField(default='', max_length=512)),
                ('tooltip_html', models.CharField(default='', max_length=2014)),
                ('tooltip_text', models.CharField(default='', max_length=512)),
                ('web_resources', models.TextField(default='', verbose_name='Target Web Resources')),
                ('web_resources_html', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, default='')),
                ('author', models.CharField(default='unknown', max_length=64, verbose_name='Ruleset Author')),
                ('author_url', models.URLField(default='', max_length=256, verbose_name='Ruleset Author URL')),
            ],
            options={
                'verbose_name': 'Ruleset',
                'verbose_name_plural': 'Rulesets',
                'ordering': ['title_text'],
            },
        ),
    ]
