# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_date', models.DateTimeField(editable=False)),
                ('ruleset_id', models.CharField(max_length=64)),
                ('version', models.CharField(default=b'unknown', max_length=16, verbose_name=b'Ruleset Version')),
                ('slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=128, verbose_name=b'Ruleset Title')),
                ('title_html', models.CharField(default=b'', max_length=512)),
                ('title_text', models.CharField(default=b'', max_length=128)),
                ('tooltip', models.CharField(default=b'', max_length=512)),
                ('tooltip_html', models.CharField(default=b'', max_length=2014)),
                ('tooltip_text', models.CharField(default=b'', max_length=512)),
                ('web_resources', models.TextField(default=b'', verbose_name=b'Target Web Resources')),
                ('web_resources_html', models.TextField(blank=True, default=b'', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, default=b'')),
                ('author', models.CharField(default=b'unknown', max_length=64, verbose_name=b'Ruleset Author')),
                ('author_url', models.URLField(default=b'', max_length=256, verbose_name=b'Ruleset Author URL')),
            ],
            options={
                'ordering': ['title_text'],
                'verbose_name': 'Ruleset',
                'verbose_name_plural': 'Rulesets',
            },
        ),
    ]
