# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rulesets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='author',
            field=models.CharField(default='unknown', max_length=64, verbose_name='Ruleset Author'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='author_url',
            field=models.URLField(default='', max_length=256, verbose_name='Ruleset Author URL'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='description_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Ruleset Title'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='title_html',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='title_text',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='tooltip',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='tooltip_html',
            field=models.CharField(default='', max_length=2014),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='tooltip_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='version',
            field=models.CharField(default='unknown', max_length=16, verbose_name='Ruleset Version'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='web_resources',
            field=models.TextField(default='', verbose_name='Target Web Resources'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='web_resources_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
