# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderesultmessage',
            name='label',
            field=models.CharField(choices=[('ELEMENT_PASS_1', 'ELEMENT_PASS_1'), ('ELEMENT_PASS_2', 'ELEMENT_PASS_2'), ('ELEMENT_PASS_3', 'ELEMENT_PASS_3'), ('ELEMENT_PASS_4', 'ELEMENT_PASS_4'), ('ELEMENT_PASS_5', 'ELEMENT_PASS_5'), ('ELEMENT_FAIL_1', 'ELEMENT_FAIL_1'), ('ELEMENT_FAIL_2', 'ELEMENT_FAIL_2'), ('ELEMENT_FAIL_3', 'ELEMENT_FAIL_3'), ('ELEMENT_FAIL_4', 'ELEMENT_FAIL_4'), ('ELEMENT_FAIL_5', 'ELEMENT_FAIL_5'), ('ELEMENT_MC_1', 'ELEMENT_MC_1'), ('ELEMENT_MC_2', 'ELEMENT_MC_2'), ('ELEMENT_MC_3', 'ELEMENT_MC_3'), ('ELEMENT_MC_4', 'ELEMENT_MC_4'), ('ELEMENT_MC_5', 'ELEMENT_MC_5'), ('ELEMENT_HIDDEN_1', 'ELEMENT_HIDDEN_1'), ('ELEMENT_HIDDEN_2', 'ELEMENT_HIDDEN_2'), ('PAGE_PASS_1', 'PAGE_PASS_1'), ('PAGE_PASS_2', 'PAGE_PASS_2'), ('PAGE_PASS_3', 'PAGE_PASS_3'), ('PAGE_PASS_4', 'PAGE_PASS_4'), ('PAGE_PASS_5', 'PAGE_PASS_5'), ('PAGE_FAIL_1', 'PAGE_FAIL_1'), ('PAGE_FAIL_2', 'PAGE_FAIL_2'), ('PAGE_FAIL_3', 'PAGE_FAIL_3'), ('PAGE_FAIL_4', 'PAGE_FAIL_4'), ('PAGE_FAIL_5', 'PAGE_FAIL_5'), ('PAGE_MC_1', 'PAGE_MC_1'), ('PAGE_MC_2', 'PAGE_MC_2'), ('PAGE_MC_3', 'PAGE_MC_3'), ('PAGE_MC_4', 'PAGE_MC_4'), ('PAGE_MC_5', 'PAGE_MC_5'), ('WEBSITE_PASS_1', 'WEBSITE_PASS_1'), ('WEBSITE_PASS_2', 'WEBSITE_PASS_2'), ('WEBSITE_PASS_3', 'WEBSITE_PASS_3'), ('WEBSITE_PASS_4', 'WEBSITE_PASS_4'), ('WEBSITE_PASS_5', 'WEBSITE_PASS_5'), ('WEBSITE_FAIL_1', 'WEBSITE_FAIL_1'), ('WEBSITE_FAIL_2', 'WEBSITE_FAIL_2'), ('WEBSITE_FAIL_3', 'WEBSITE_FAIL_3'), ('WEBSITE_FAIL_4', 'WEBSITE_FAIL_4'), ('WEBSITE_FAIL_5', 'WEBSITE_FAIL_5'), ('WEBSITE_MC_1', 'WEBSITE_MC_1'), ('WEBSITE_MC_2', 'WEBSITE_MC_2'), ('WEBSITE_MC_3', 'WEBSITE_MC_3'), ('WEBSITE_MC_4', 'WEBSITE_MC_4'), ('WEBSITE_MC_5', 'WEBSITE_MC_5')], max_length=32, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='noderesultmessage',
            name='message',
            field=models.CharField(max_length=512, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='definition',
            field=models.CharField(max_length=512, verbose_name='Rule Definition'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='definition_html',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='rule',
            name='informational_links',
            field=models.TextField(default='', verbose_name='Informational Links'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='informational_links_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='language_dependancy',
            field=models.CharField(default='', max_length=100, verbose_name='Language codes separated by commas'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='manual_checks',
            field=models.TextField(default='', verbose_name='Manual Checks'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='manual_checks_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='nls_rule_id',
            field=models.CharField(max_length=64, verbose_name='Translated Rule ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='primary_property',
            field=models.CharField(default='', max_length=64, verbose_name='primary attribute or property used by the rule'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='purpose',
            field=models.TextField(default='', verbose_name='Purpose (i.e how does the rule help people with disabilites)'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='purpose_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='resource_properties',
            field=models.CharField(max_length=250, verbose_name='Comma separated list of cache properties and attributes used by the rule'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='Rule ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_fail_p',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: More than one failed element'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_fail_s',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: One failed element'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_hidden_p',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: More than one hidden element'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_hidden_s',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: One hidden element'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_mc_p',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: More than one manual check'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_mc_s',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: One manual check'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_result_na',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Rule Result Message: Not Applicable Message'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='slug',
            field=models.SlugField(blank=True, default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='rule',
            name='summary',
            field=models.CharField(max_length=128, verbose_name='Rule Summary (shorter version of definition)'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='summary_html',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rule',
            name='summary_text',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rule',
            name='target_resource_desc',
            field=models.CharField(max_length=512, verbose_name='Summary of the types of element definitions this rule tests'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='techniques',
            field=models.TextField(default='', verbose_name='Techniques'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='techniques_html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='validation',
            field=models.TextField(blank=True, null=True, verbose_name='Javascript code for validation function'),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='description',
            field=models.CharField(default='', max_length=2048, verbose_name='Group Description'),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='rule_group_code',
            field=models.IntegerField(default=0, verbose_name='Group Code'),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='title',
            field=models.CharField(default='none', max_length=32, verbose_name='Group Title'),
        ),
        migrations.AlterField(
            model_name='rulescope',
            name='abbrev',
            field=models.CharField(default='none', max_length=32, verbose_name='Scope Abbreviation'),
        ),
        migrations.AlterField(
            model_name='rulescope',
            name='description',
            field=models.CharField(default='', max_length=2048, verbose_name='Scope Description'),
        ),
        migrations.AlterField(
            model_name='rulescope',
            name='rule_scope_code',
            field=models.IntegerField(default=0, verbose_name='Scope Code'),
        ),
        migrations.AlterField(
            model_name='rulescope',
            name='slug',
            field=models.SlugField(blank=True, default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='rulescope',
            name='title',
            field=models.CharField(default='none', max_length=128, verbose_name='Scope Title'),
        ),
    ]
