#!/bin/bash

echo $FAE_HOME

HP=$FAE_HOME/lib/htmlunit-2.45.0/lib/*.jar

echo $HP

CLASSPATH=$FAE_HOME
echo $CLASSPATH

for f in $HP;
do
  echo "Adding $f to classpath";
  CLASSPATH=$CLASSPATH:$f;
done

export CLASSPATH

