#!/bin/bash

CP=$FAE_HOME/lib/commons-cli-1.2
HP=$FAE_HOME/lib/htmlunit-2.33/lib

CLASSPATH=$FAE_HOME

CLASSPATH=$CLASSPATH:$FAE_HOME/lib/log4j.jar

CLASSPATH=$CLASSPATH:$CP/commons-cli-1.2.jar

for f in $HP/*.jar; do echo "Adding $f to classpath"; CLASSPATH=$CLASSPATH:$f; done

export CLASSPATH

