# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    replaces = [(b'userProfiles', '0001_initial'), (b'userProfiles', '0002_auto_20160106_0900'), (b'userProfiles', '0003_auto_20160107_1301'), (b'userProfiles', '0004_userprofile_ws_report_group'), (b'userProfiles', '0005_auto_20160204_2227')]

    initial = True

    dependencies = [
        ('websiteResultGroups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Maximum')], default=1)),
                ('org', models.CharField(blank=True, max_length=128)),
                ('email_announcements', models.BooleanField(default=True)),
                ('multiple_urls_enabled', models.BooleanField(default=False)),
                ('website_authorization_enabled', models.BooleanField(default=False)),
                ('advanced_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('max_archive', models.IntegerField(default=5)),
                ('max_saved', models.IntegerField(default=10)),
                ('timezone', timezone_field.fields.TimeZoneField(default='America/Chicago')),
                ('ws_report_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup')),
            ],
        ),
    ]
