# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=b'no account type title', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, default=b'')),
                ('level', models.IntegerField(default=10)),
                ('max_archive', models.IntegerField(default=10)),
                ('max_permanent', models.IntegerField(default=5)),
                ('max_depth', models.IntegerField(default=2)),
                ('max_pages', models.IntegerField(default=25)),
                ('advanced', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level'],
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='acct_expires',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acct_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='userProfiles.AccountType'),
        ),
    ]
