# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_archive',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_saved',
            field=models.IntegerField(default=10),
        ),
    ]
