# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_saved',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_permanent',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_archive',
            field=models.IntegerField(default=10),
        ),
    ]
