# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ws_report_group',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup'),
        ),
    ]
