# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_auto_20160701_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['acc_type'], 'verbose_name': 'Account Type', 'verbose_name_plural': 'Account Types'},
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='level',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='acc_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acct_expires',
            field=timezone_field.fields.TimeZoneField(default=b'America/Chicago'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='userProfiles.AccountType'),
        ),
    ]
