# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_auto_20160725_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_amount',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_start',
        ),
    ]
