# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0003_auto_20160830_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
