# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteResultGroups', '0001_initial'),
        ('userProfiles', '0003_auto_20160107_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ws_report_group',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='websiteResultGroups.WebsiteReportGroup'),
        ),
    ]
