# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0003_auto_20160704_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
