# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0003_auto_20160209_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ws_report_group',
        ),
    ]
