# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0004_auto_20160704_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='advanced_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_archive',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_permanent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='multiple_urls_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website_authorization_enabled',
        ),
    ]
