# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0004_remove_userprofile_ws_report_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
