# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0004_auto_20160831_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_daily_rate',
            field=models.IntegerField(default=0),
        ),
    ]
