# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0005_userprofile_subscription_daily_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_any_account_types',
            field=models.BooleanField(default=False),
        ),
    ]
