# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0005_auto_20160704_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['type_id'], 'verbose_name': 'Account Type', 'verbose_name_plural': 'Account Types'},
        ),
        migrations.RenameField(
            model_name='accounttype',
            old_name='acc_type',
            new_name='type_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='acct_expires',
            new_name='account_expires',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='acct_type',
            new_name='account_type',
        ),
    ]
