# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0006_userprofile_enable_any_account_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[(b'NEVER', b'Never subscribed'), (b'CURRENT', b'Current'), (b'EXPIRED', b'Expired')], default=b'NEVER', max_length=8),
        ),
    ]
