# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0006_auto_20160705_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='accounts.AccountType'),
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
    ]
