# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0007_userprofile_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_days',
            field=models.IntegerField(default=0),
        ),
    ]
