# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0008_userprofile_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_level_domain',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'CURRENT', b'Current'), (b'EXPIRED', b'Expired')], default=b'FREE', max_length=8),
        ),
    ]
