# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttype_next_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfiles', '0009_auto_20161019_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact1_name', models.CharField(blank=True, default=b'', max_length=32)),
                ('contact1_title', models.CharField(blank=True, default=b'', max_length=32)),
                ('contact1_email', models.EmailField(blank=True, default=b'', max_length=64)),
                ('contact1_phone', models.CharField(blank=True, default=b'', max_length=16)),
                ('contact2_name', models.CharField(blank=True, default=b'', max_length=32)),
                ('contact2_title', models.CharField(blank=True, default=b'', max_length=32)),
                ('contact2_email', models.EmailField(blank=True, default=b'', max_length=64)),
                ('contact2_phone', models.CharField(blank=True, default=b'', max_length=16)),
                ('top_level_domain', models.CharField(blank=True, default=b'', max_length=8)),
                ('domain', models.CharField(blank=True, default=b'', max_length=64)),
                ('alt_domain', models.CharField(blank=True, default=b'', max_length=64)),
                ('subscription_status', models.CharField(choices=[(b'FREE', b'Free'), (b'CURRENT', b'Current'), (b'EXPIRED', b'Expired')], default=b'FREE', max_length=8)),
                ('subscription_days', models.IntegerField(default=0)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('subscription_payment', models.IntegerField(default=0)),
                ('last_payment', models.IntegerField(default=0)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institional_subscriptions', to='accounts.AccountType')),
                ('users', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_type'],
                'verbose_name': 'Institutional Subscription',
                'verbose_name_plural': 'Institutional Subscriptions',
            },
        ),
    ]
