# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0010_institutionalprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionalprofile',
            options={'ordering': ['account_type'], 'verbose_name': 'Institutional Profile', 'verbose_name_plural': 'Institutional Profiles'},
        ),
        migrations.AddField(
            model_name='institutionalprofile',
            name='title',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='institutionalprofile',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='institional_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
