# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0011_auto_20161102_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalprofile',
            name='subscription_status',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'CURRENT', b'Current'), (b'EXPIRED', b'Expired'), (b'SPECIAL', b'Special')], default=b'FREE', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[(b'FREE', b'Free'), (b'CURRENT', b'Current'), (b'EXPIRED', b'Expired'), (b'SPECIAL', b'Special')], default=b'FREE', max_length=8),
        ),
    ]
