# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0012_auto_20170209_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalprofile',
            name='authentication',
            field=models.CharField(blank=True, default=b'', max_length=64),
        ),
    ]
