# Generated by Django 2.2.7 on 2019-12-18 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rulesets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedURL',
            fields=[
                ('excluded_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(default='', max_length=256, verbose_name='File Type')),
                ('url', models.URLField(max_length=4096, verbose_name='Excluded URL')),
                ('file_type', models.CharField(default='', max_length=16, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'URL: Excluded URL',
                'verbose_name_plural': 'URL: Excluded URL',
                'ordering': ['file_type', 'url'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteReport',
            fields=[
                ('result_value', models.IntegerField(default=0)),
                ('implementation_pass_fail_score', models.IntegerField(default=-1)),
                ('implementation_score', models.IntegerField(default=-1)),
                ('implementation_pass_fail_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status')),
                ('implementation_status', models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status')),
                ('manual_check_status', models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status')),
                ('rules_violation', models.IntegerField(default=0)),
                ('rules_warning', models.IntegerField(default=0)),
                ('rules_manual_check', models.IntegerField(default=0)),
                ('rules_passed', models.IntegerField(default=0)),
                ('rules_na', models.IntegerField(default=0)),
                ('rules_with_hidden_content', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=256, unique=True)),
                ('title', models.CharField(default='', max_length=1024, verbose_name='Title')),
                ('url', models.URLField(default='', max_length=1024, verbose_name='URL')),
                ('follow', models.IntegerField(choices=[(1, 'Specified domain only'), (2, 'Next-level subdomains'), (3, 'Include or exclude based on set of domains')], default=1, verbose_name='Follow Links In')),
                ('depth', models.IntegerField(choices=[(1, 'Top-level page only'), (2, 'Include second-level pages'), (3, 'Include third-level pages'), (4, 'Include fourth-level pages'), (5, 'Include fifth-level pages'), (6, 'Include six-level pages')], default=2, verbose_name='Depth of Evaluation')),
                ('max_pages', models.IntegerField(choices=[(5, '    5 pages'), (10, '   10 pages'), (25, '   25 pages'), (50, '   50 pages'), (100, '  100 pages'), (200, '  200 pages'), (400, '  400 pages'), (800, '  800 pages'), (1600, ' 1600 pages'), (3200, ' 3200 pages'), (6400, ' 6400 pages')], default=0, verbose_name='Evaluation Limited To')),
                ('browser_emulation', models.CharField(default='FIREFOX', max_length=32, verbose_name='Browser Emulation')),
                ('wait_time', models.IntegerField(choices=[(30000, ' 30 seconds'), (45000, ' 45 seconds'), (60000, ' 60 seconds'), (90000, ' 90 seconds'), (120000, '120 seconds')], default=90000, verbose_name='How long to wait for website to load resources')),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=16, verbose_name='Protocol')),
                ('domain', models.CharField(blank=True, default='', max_length=1024, verbose_name='Domain')),
                ('require_path', models.BooleanField(default=False)),
                ('path', models.CharField(blank=True, default='', max_length=1024, verbose_name='Path')),
                ('more_urls', models.BooleanField(default=False)),
                ('enable_next_level_sub_domains', models.BooleanField(default=False)),
                ('enable_span_sub_domains', models.BooleanField(default=False)),
                ('enable_exclude_domains', models.BooleanField(default=False)),
                ('enable_include_domains', models.BooleanField(default=False)),
                ('span_sub_domains', models.CharField(blank=True, default='', max_length=1024, verbose_name='Other next-level subdomains (space separated)')),
                ('exclude_domains', models.CharField(blank=True, default='', max_length=1024, verbose_name='Exclude domains (space separated)')),
                ('include_domains', models.CharField(blank=True, default='', max_length=1024, verbose_name='Include domains (space separated)')),
                ('authorization', models.TextField(blank=True, default='', max_length=8192, verbose_name='Authentication Information')),
                ('page_count', models.IntegerField(default=0, verbose_name='Number of Pages')),
                ('archive', models.BooleanField(default=False)),
                ('delete_flag', models.BooleanField(default=False)),
                ('stats', models.BooleanField(default=False)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('last_report_type', models.CharField(choices=[('rules', 'Summary'), ('pages', 'All Pages'), ('page', 'Page')], default='rules', max_length=16, verbose_name='Last Report Type')),
                ('last_view', models.CharField(choices=[('rc', 'Rule Category'), ('gl', 'WCAG Guideline'), ('rs', 'Rule Scope')], default='rc', max_length=4, verbose_name='Last Viewed')),
                ('last_group', models.CharField(default='', max_length=32, verbose_name='Last Group')),
                ('last_page', models.IntegerField(default=1, verbose_name='Last Page Viewed')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('-', 'Created'), ('I', 'Initalized'), ('A', 'Analyzing'), ('S', 'Saving'), ('C', 'Complete'), ('E', 'Error'), ('D', 'Marked for deletion'), ('SUM', 'Archived for summary stats')], default='-', max_length=10, verbose_name='Status')),
                ('processing_time', models.IntegerField(default=-1)),
                ('processed_urls_count', models.IntegerField(default=-1)),
                ('unprocessed_urls_count', models.IntegerField(default=-1)),
                ('filtered_urls_count', models.IntegerField(default=-1)),
                ('data_dir_slug', models.SlugField(editable=False)),
                ('data_directory', models.CharField(default='', max_length=1024, verbose_name='Data Directory')),
                ('data_property_file', models.CharField(default='', max_length=1024, verbose_name='Property File Name')),
                ('data_authorization_file', models.CharField(blank=True, default='', max_length=1024, verbose_name='Authorization File Name')),
                ('data_multiple_urls_file', models.CharField(blank=True, default='', max_length=1024, verbose_name='Multiple URLs File Name')),
                ('log_file', models.CharField(default='', max_length=1024, verbose_name='Log file')),
                ('ruleset', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rulesets.Ruleset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-archive', '-created'],
            },
        ),
        migrations.CreateModel(
            name='UnprocessedURL',
            fields=[
                ('unprocessed_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=4096, verbose_name='Unprocessed URL')),
                ('url_referenced', models.URLField(max_length=4096, verbose_name='Referenced URL')),
                ('dom_time', models.IntegerField(verbose_name='Loading DOM time')),
                ('link_time', models.IntegerField(verbose_name='Retreive links tIme')),
                ('event_time', models.IntegerField(verbose_name='Event time')),
                ('eval_time', models.IntegerField(verbose_name='Evaluation time')),
                ('save_time', models.IntegerField(verbose_name='Saving results time')),
                ('total_time', models.IntegerField(verbose_name='Total processing time')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unprocessed_urls', to='reports.WebsiteReport')),
            ],
            options={
                'verbose_name': 'URL: Unprocessed',
                'verbose_name_plural': 'URL: Unprocessed',
                'ordering': ['url', 'url_referenced'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedURL',
            fields=[
                ('processed_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_seq_num', models.IntegerField(default=-1)),
                ('url_requested', models.URLField(max_length=4096, verbose_name='Processed URL')),
                ('url_returned', models.URLField(max_length=4096, verbose_name='Returned URL')),
                ('redirect', models.BooleanField(default=False, verbose_name='Server redirect')),
                ('http_status_code', models.IntegerField(verbose_name='http status code')),
                ('url_referenced', models.URLField(max_length=4096, verbose_name='Referenced URL')),
                ('dom_time', models.IntegerField(verbose_name='Loading DOM time')),
                ('link_time', models.IntegerField(verbose_name='Retreive links tIme')),
                ('event_time', models.IntegerField(verbose_name='Event time')),
                ('eval_time', models.IntegerField(verbose_name='Evaluation time')),
                ('save_time', models.IntegerField(verbose_name='Saving results time')),
                ('total_time', models.IntegerField(verbose_name='Total processing time')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_urls', to='reports.WebsiteReport')),
            ],
            options={
                'verbose_name': 'URL: Processed',
                'verbose_name_plural': 'URL: Processed',
                'ordering': ['http_status_code', 'url_returned', 'total_time'],
            },
        ),
        migrations.CreateModel(
            name='FilteredURL',
            fields=[
                ('filtered_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=4096, verbose_name='Other URL')),
                ('url_referenced', models.URLField(max_length=4096, verbose_name='Referenced URL')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_urls', to='reports.WebsiteReport')),
            ],
            options={
                'verbose_name': 'URL: Filtered',
                'verbose_name_plural': 'URL: Filtered',
                'ordering': ['url_referenced', 'url'],
            },
        ),
        migrations.CreateModel(
            name='ExcludedURLPageReference',
            fields=[
                ('page_reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=4096, verbose_name='Excluded URL')),
                ('excluded_urls', models.ManyToManyField(related_name='excluded_url_page_refs', to='reports.ExcludedURL')),
                ('ws_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_url_page_refs', to='reports.WebsiteReport')),
            ],
            options={
                'verbose_name': 'URL: Page Reference for Excluded URLs',
                'verbose_name_plural': 'URL: Page Reference for Excluded URLs',
                'ordering': ['url'],
            },
        ),
        migrations.AddField(
            model_name='excludedurl',
            name='ws_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_urls', to='reports.WebsiteReport'),
        ),
    ]
