# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitereport',
            options={'ordering': ['-created'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='websitereport',
            name='last_page',
            field=models.IntegerField(default=1, verbose_name='Last Page Viewed'),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='last_view',
            field=models.CharField(default='rc', max_length=4, verbose_name='Last View'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='max_pages',
            field=models.IntegerField(choices=[(0, ' All pages'), (5, '   5 pages'), (10, '  10 pages'), (25, '  25 pages')], default=0, verbose_name='Analyze Pages'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='title',
            field=models.CharField(default='', max_length=1024, verbose_name='Title'),
        ),
    ]
