# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
