# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20151223_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='last_next_page',
            field=models.IntegerField(default=0, verbose_name='Last Page Viewed'),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='last_prev_page',
            field=models.IntegerField(default=0, verbose_name='Last Page Viewed'),
        ),
    ]
