# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160917_1006'),
        ('reports', '0002_auto_20161019_1419'),
    ]

    operations = [
    ]
