# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20160310_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitereport',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'NI-MC', b'Not Implemented with manual checks required'), (b'PI-MC', b'Partial Implementation with manual checks required'), (b'AC-MC', b'Almost Complete with manual checks required'), (b'C', b'Complete')], default=b'U', max_length=8, verbose_name=b'Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='implementation_status',
            field=models.CharField(choices=[(b'U', b'Undefined'), (b'NA', b'Not applicable'), (b'NI', b'Not Implemented'), (b'PI', b'Partial Implementation'), (b'AC', b'Almost Complete'), (b'NI-MC', b'Not Implemented with manual checks required'), (b'PI-MC', b'Partial Implementation with manual checks required'), (b'AC-MC', b'Almost Complete with manual checks required'), (b'C', b'Complete')], default=b'U', max_length=8, verbose_name=b'Implementation Status'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_group',
            field=models.CharField(default=b'', max_length=32, verbose_name=b'Last Group'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_report_type',
            field=models.CharField(choices=[(b'rules', b'Summary'), (b'pages', b'All Pages'), (b'page', b'Page')], default=b'rules', max_length=16, verbose_name=b'Last Report Type'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_view',
            field=models.CharField(choices=[(b'rc', b'Rule Category'), (b'gl', b'WCAG Guideline'), (b'rs', b'Rule Scope')], default=b'rc', max_length=4, verbose_name=b'Last Viewed'),
        ),
    ]
