# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20161019_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='path',
            field=models.CharField(blank=True, default=b'', max_length=1024, verbose_name=b'Path'),
        ),
    ]
