# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20161212_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitereport',
            name='scheme',
        ),
        migrations.AddField(
            model_name='websitereport',
            name='protocol',
            field=models.CharField(blank=True, choices=[(b'http', b'http'), (b'https', b'https')], default=b'http', max_length=16, verbose_name=b'Protocol'),
        ),
    ]
