# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20151223_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
