# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_websitereport_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitereport',
            old_name='last_next_page_url',
            new_name='next_page_url',
        ),
        migrations.RenameField(
            model_name='websitereport',
            old_name='last_prev_page_url',
            new_name='prev_page_url',
        ),
        migrations.AddField(
            model_name='websitereport',
            name='first_page_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='First Page URL'),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='last_page_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='Last Page URL'),
        ),
    ]
