# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20161212_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='more_urls',
            field=models.BooleanField(default=False),
        ),
    ]
