# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20160113_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='last_first_page',
            field=models.IntegerField(default=0, verbose_name='Next Page Number'),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='last_last_page',
            field=models.IntegerField(default=0, verbose_name='Previous Page Number'),
        ),
    ]
