# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_websitereport_more_urls'),
        ('reports', '0003_merge'),
    ]

    operations = [
    ]
