# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20170103_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitereport',
            name='exclude_sub_domains',
        ),
        migrations.AddField(
            model_name='websitereport',
            name='exclude_domains',
            field=models.CharField(blank=True, default=b'', max_length=1024, verbose_name=b'Exclude Domains (space separated)'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='follow',
            field=models.IntegerField(choices=[(1, b'Specified domain only'), (2, b'Next-level subdomains'), (3, b'Include or exclude based on set of domains')], default=1, verbose_name=b'Follow Links in'),
        ),
    ]
