# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170105_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitereport',
            name='enable_exclude_domains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='enable_include_domains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='enable_next_level_sub_domains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websitereport',
            name='enable_span_sub_domains',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='exclude_domains',
            field=models.CharField(blank=True, default=b'', max_length=1024, verbose_name=b'Exclude domains (space separated)'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='follow',
            field=models.IntegerField(choices=[(1, b'Specified domain only'), (2, b'Next-level subdomains'), (3, b'Include or exclude based on set of domains')], default=1, verbose_name=b'Follow Links In'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='include_domains',
            field=models.CharField(blank=True, default=b'', max_length=1024, verbose_name=b'Include domains (space separated)'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='span_sub_domains',
            field=models.CharField(blank=True, default=b'', max_length=1024, verbose_name=b'Other next-level subdomains (space separated)'),
        ),
    ]
