# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_merge'),
        ('reports', '0008_auto_20170105_1133'),
    ]

    operations = [
    ]
