# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20160127_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitereport',
            name='status',
            field=models.CharField(choices=[(b'-', b'Created'), (b'I', b'Initalized'), (b'A', b'Analyzing'), (b'S', b'Saving'), (b'C', b'Complete'), (b'E', b'Error'), (b'SUM', b'Summary')], default=b'-', max_length=10, verbose_name=b'Status'),
        ),
    ]
