# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20170109_2038'),
        ('reports', '0009_merge'),
    ]

    operations = [
    ]
