# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-21 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170209_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excludedurl',
            options={'ordering': ['first_reference_url', 'url'], 'verbose_name': 'URL: Excluded', 'verbose_name_plural': 'URL: Excluded'},
        ),
        migrations.RenameField(
            model_name='excludedurl',
            old_name='url_referenced',
            new_name='first_reference_url',
        ),
        migrations.AddField(
            model_name='excludedurl',
            name='reference_count',
            field=models.IntegerField(default=0, verbose_name=b'Number of times URL referenced'),
        ),
    ]
