# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_merge'),
        ('reports', '0011_auto_20170220_2042'),
    ]

    operations = [
    ]
