# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20170220_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedurl',
            name='reference_count',
            field=models.IntegerField(default=1, verbose_name=b'Number of times URL referenced'),
        ),
        migrations.AlterField(
            model_name='excludedurl',
            name='url',
            field=models.URLField(max_length=4096, verbose_name=b'Excluded URL'),
        ),
    ]
