# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20170226_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedURLPageReference',
            fields=[
                ('page_reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=4096, verbose_name=b'Excluded URL')),
            ],
            options={
                'ordering': ['url'],
                'verbose_name': 'URL: Page Reference',
                'verbose_name_plural': 'URL: Page Reference',
            },
        ),
        migrations.AlterModelOptions(
            name='excludedurl',
            options={'ordering': ['file_type', 'reference_count', 'url'], 'verbose_name': 'URL: Excluded', 'verbose_name_plural': 'URL: Excluded'},
        ),
        migrations.RenameField(
            model_name='excludedurl',
            old_name='filtered_url_id',
            new_name='excluded_url_id',
        ),
        migrations.RemoveField(
            model_name='excludedurl',
            name='first_reference_url',
        ),
        migrations.AddField(
            model_name='excludedurlpagereference',
            name='excluded_urls',
            field=models.ManyToManyField(related_name='excluded_url_page_refs', to='reports.ExcludedURL'),
        ),
        migrations.AddField(
            model_name='excludedurlpagereference',
            name='ws_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_url_page_refs', to='reports.WebsiteReport'),
        ),
    ]
