# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_merge'),
        ('reports', '0014_auto_20170301_0647'),
    ]

    operations = [
    ]
