# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20170914_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excludedurl',
            name='file_type',
            field=models.CharField(default='', max_length=16, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='excludedurl',
            name='filename',
            field=models.CharField(default='', max_length=256, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='excludedurl',
            name='url',
            field=models.URLField(max_length=4096, verbose_name='Excluded URL'),
        ),
        migrations.AlterField(
            model_name='excludedurlpagereference',
            name='url',
            field=models.URLField(max_length=4096, verbose_name='Excluded URL'),
        ),
        migrations.AlterField(
            model_name='filteredurl',
            name='url',
            field=models.URLField(max_length=4096, verbose_name='Other URL'),
        ),
        migrations.AlterField(
            model_name='filteredurl',
            name='url_referenced',
            field=models.URLField(max_length=4096, verbose_name='Referenced URL'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='dom_time',
            field=models.IntegerField(verbose_name='Loading DOM time'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='eval_time',
            field=models.IntegerField(verbose_name='Evaluation time'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='event_time',
            field=models.IntegerField(verbose_name='Event time'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='http_status_code',
            field=models.IntegerField(verbose_name='http status code'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='link_time',
            field=models.IntegerField(verbose_name='Retreive links tIme'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='redirect',
            field=models.BooleanField(default=False, verbose_name='Server redirect'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='save_time',
            field=models.IntegerField(verbose_name='Saving results time'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='total_time',
            field=models.IntegerField(verbose_name='Total processing time'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='url_referenced',
            field=models.URLField(max_length=4096, verbose_name='Referenced URL'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='url_requested',
            field=models.URLField(max_length=4096, verbose_name='Processed URL'),
        ),
        migrations.AlterField(
            model_name='processedurl',
            name='url_returned',
            field=models.URLField(max_length=4096, verbose_name='Returned URL'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='dom_time',
            field=models.IntegerField(verbose_name='Loading DOM time'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='eval_time',
            field=models.IntegerField(verbose_name='Evaluation time'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='event_time',
            field=models.IntegerField(verbose_name='Event time'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='link_time',
            field=models.IntegerField(verbose_name='Retreive links tIme'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='save_time',
            field=models.IntegerField(verbose_name='Saving results time'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='total_time',
            field=models.IntegerField(verbose_name='Total processing time'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='url',
            field=models.URLField(max_length=4096, verbose_name='Unprocessed URL'),
        ),
        migrations.AlterField(
            model_name='unprocessedurl',
            name='url_referenced',
            field=models.URLField(max_length=4096, verbose_name='Referenced URL'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='authorization',
            field=models.TextField(blank=True, default='', max_length=8192, verbose_name='Authentication Information'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='browser_emulation',
            field=models.CharField(default='FIREFOX', max_length=32, verbose_name='Browser Emulation'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='data_authorization_file',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Authorization File Name'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='data_directory',
            field=models.CharField(default='', max_length=1024, verbose_name='Data Directory'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='data_multiple_urls_file',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Multiple URLs File Name'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='data_property_file',
            field=models.CharField(default='', max_length=1024, verbose_name='Property File Name'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='depth',
            field=models.IntegerField(choices=[(1, 'Top-level page only'), (2, 'Include second-level pages'), (3, 'Include third-level pages'), (4, 'Include fourth-level pages'), (5, 'Include fifth-level pages'), (6, 'Include six-level pages')], default=2, verbose_name='Depth of Evaluation'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='exclude_domains',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Exclude domains (space separated)'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='follow',
            field=models.IntegerField(choices=[(1, 'Specified domain only'), (2, 'Next-level subdomains'), (3, 'Include or exclude based on set of domains')], default=1, verbose_name='Follow Links In'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='include_domains',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Include domains (space separated)'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_group',
            field=models.CharField(default='', max_length=32, verbose_name='Last Group'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_page',
            field=models.IntegerField(default=1, verbose_name='Last Page Viewed'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_report_type',
            field=models.CharField(choices=[('rules', 'Summary'), ('pages', 'All Pages'), ('page', 'Page')], default='rules', max_length=16, verbose_name='Last Report Type'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='last_view',
            field=models.CharField(choices=[('rc', 'Rule Category'), ('gl', 'WCAG Guideline'), ('rs', 'Rule Scope')], default='rc', max_length=4, verbose_name='Last Viewed'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='log_file',
            field=models.CharField(default='', max_length=1024, verbose_name='Log file'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='max_pages',
            field=models.IntegerField(choices=[(5, '    5 pages'), (10, '   10 pages'), (25, '   25 pages'), (50, '   50 pages'), (100, '  100 pages'), (200, '  200 pages'), (400, '  400 pages'), (800, '  800 pages'), (1600, ' 1600 pages'), (3200, ' 3200 pages'), (6400, ' 6400 pages')], default=0, verbose_name='Evaluation Limited To'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='page_count',
            field=models.IntegerField(default=0, verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='path',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=16, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='span_sub_domains',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Other next-level subdomains (space separated)'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='status',
            field=models.CharField(choices=[('-', 'Created'), ('I', 'Initalized'), ('A', 'Analyzing'), ('S', 'Saving'), ('C', 'Complete'), ('E', 'Error'), ('D', 'Marked for deletion'), ('SUM', 'Archived for summary stats')], default='-', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='title',
            field=models.CharField(default='', max_length=1024, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='url',
            field=models.URLField(default='', max_length=1024, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='websitereport',
            name='wait_time',
            field=models.IntegerField(choices=[(30000, ' 30 seconds'), (45000, ' 45 seconds'), (60000, ' 60 seconds'), (90000, ' 90 seconds'), (120000, '120 seconds')], default=90000, verbose_name='How long to wait for website to load resources'),
        ),
    ]
