# Generated by Django 2.2.7 on 2019-12-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_id', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='')),
                ('one_month', models.IntegerField(default=0)),
                ('three_month', models.IntegerField(default=0)),
                ('six_month', models.IntegerField(default=0)),
                ('twelve_month', models.IntegerField(default=0)),
                ('account_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_rate', to='accounts.AccountType')),
            ],
            options={
                'verbose_name': 'Subscription Rate',
                'verbose_name_plural': 'Subscription Rates',
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New un-initialized payment transaction'), ('PMT_REGISTERED', 'Payment registered'), ('PMT_APPROV', 'Payment approved'), ('PMT_CANCELLED', 'Payment cancelled by user'), ('PMT_MAX_ATTEMPT', 'Payment max attempts'), ('PMT_EXPIRED', 'Payment token expired'), ('PMT_SESSION', 'Payment session error'), ('PMT_ERROR', 'Payment error'), ('PMT_NOCOST', 'No cost change')], default='NEW', max_length=16)),
                ('subscription_balance', models.IntegerField(default=0)),
                ('profile_subscription_end', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('subscription_cost', models.IntegerField(default=0)),
                ('actual_subscription_cost', models.IntegerField(default=0)),
                ('subscription_duration', models.CharField(choices=[('1', 'One month'), ('3', 'Three months'), ('6', 'Six months'), ('12', 'Twelve months')], default='1', max_length=4)),
                ('reconciliation', models.IntegerField(default=-1)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(default='', max_length=13)),
                ('token', models.CharField(default='', max_length=48)),
                ('redirect_url', models.URLField(blank=True, max_length=256)),
                ('reference_time', models.DateTimeField(auto_now_add=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('register_response_code', models.IntegerField(default=-1)),
                ('register_response_msg', models.CharField(blank=True, max_length=2048)),
                ('capture_time', models.DateTimeField(blank=True, null=True)),
                ('capture_response_code', models.IntegerField(default=-1)),
                ('capture_response_msg', models.CharField(blank=True, max_length=2048)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.AccountType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['reference_time', 'capture_time'],
            },
        ),
    ]
