# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20160725_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='actual_subscription_cost',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='account_expiration_date',
            new_name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_cost',
            field=models.IntegerField(default=-1),
        ),
    ]
