# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20160726_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_duration',
            field=models.IntegerField(default=-1),
        ),
    ]
