# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_payment_subscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription_duration',
            field=models.CharField(choices=[('1', 'One month'), ('3', 'Three months'), ('6', 'Six months'), ('12', 'Twelve months')], default='1', max_length=4),
        ),
    ]
