# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_payment_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='capture_response_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='query_response_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='register_response_code',
            field=models.IntegerField(default=0),
        ),
    ]
