# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20160805_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='capture_response_code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='query_response_code',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='register_response_code',
            field=models.IntegerField(default=-1),
        ),
    ]
