# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20160805_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='query_response_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='query_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='capture_response_msg',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='payment',
            name='register_response_msg',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_balance',
            field=models.IntegerField(default=0),
        ),
    ]
