# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttype_next_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0013_auto_20160830_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitionalSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact1_name', models.CharField(blank=True, default='', max_length=32)),
                ('contact1_title', models.CharField(blank=True, default='', max_length=32)),
                ('contact1_email', models.EmailField(blank=True, default='', max_length=64)),
                ('contact1_phone', models.CharField(blank=True, default='', max_length=16)),
                ('contact2_name', models.CharField(blank=True, default='', max_length=32)),
                ('contact2_title', models.CharField(blank=True, default='', max_length=32)),
                ('contact2_email', models.EmailField(blank=True, default='', max_length=64)),
                ('contact2_phone', models.CharField(blank=True, default='', max_length=16)),
                ('domain', models.CharField(blank=True, default='', max_length=64)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('subscription_payment', models.IntegerField(default=0)),
                ('last_payment', models.IntegerField(default=0)),
                ('account_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institional_subscriptions', to='accounts.AccountType')),
                ('users', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account_type'],
                'verbose_name': 'Institutional Subscription',
                'verbose_name_plural': 'Institutional Subscriptions',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NEW', 'New un-initialized payment transaction'), ('PMT_REGISTERED', 'Payment registered'), ('PMT_APPROV', 'Payment approved'), ('PMT_CANCELLED', 'Payment cancelled by user'), ('PMT_MAX_ATTEMPT', 'Payment max attempts'), ('PMT_EXPIRED', 'Payment token expired'), ('PMT_SESSION', 'Payment session error'), ('PMT_ERROR', 'Payment error'), ('PMT_NOCOST', 'No cost change')], default='NEW', max_length=16),
        ),
    ]
