# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20160830_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NEW', 'New un-initialized payment transaction'), ('PMT_REGISTERED', 'Payment registered'), ('PMT_APPROV', 'Payment approved'), ('PMT_CANCELLED', 'Payment cancelled by user'), ('PMT_MAX_ATTEMPT', 'Payment max attempts'), ('PMT_EXPIRED', 'Payment token expired'), ('PMT_SESSION', 'Payment session error'), ('PMT_ERROR', 'Payment error'), ('PMT_NOCOST', 'No cost change')], default='NEW', max_length=16),
        ),
    ]
