# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20161017_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalsubscription',
            name='top_level_domain',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
