# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20161017_1615'),
        ('subscriptions', '0014_auto_20160907_0907'),
    ]

    operations = [
    ]
