# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_institutionalsubscription_top_level_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalsubscription',
            name='alt_domain',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
