# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_merge'),
        ('subscriptions', '0016_institutionalsubscription_top_level_domain'),
    ]

    operations = [
    ]
