# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_merge'),
        ('subscriptions', '0019_auto_20161020_1928'),
    ]

    operations = [
    ]
