# Generated by Django 2.2.7 on 2019-12-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('element_based', models.BooleanField(default=True, verbose_name='Element based markup (otherwise property based, i.e. CSS)')),
                ('url', models.URLField(blank=True, null=True)),
                ('url_slug', models.SlugField(max_length=32)),
                ('link_text', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Language Specification',
                'verbose_name_plural': 'Language Specifications',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ElementDefinition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element', models.CharField(blank=True, default='', max_length=32)),
                ('attribute', models.CharField(blank=True, default='', max_length=32)),
                ('value', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('type', models.CharField(choices=[('NONE', 'not any special type'), ('ROLE', 'ARIA Role'), ('PROP', 'ARIA Property'), ('STAT', 'ARIA State'), ('EVNT', 'Event'), ('FONT', 'CSS Font'), ('COLR', 'CSS Color'), ('POS', 'CSS Position'), ('HIGH', 'CSS Highlight'), ('CONT', 'CSS Content')], default='NONE', max_length=4)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='markup.LanguageSpec')),
            ],
            options={
                'verbose_name': 'Element Definition',
                'verbose_name_plural': 'Element Definitions',
                'ordering': ['element', 'attribute', 'value'],
            },
        ),
    ]
