# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdefinition',
            name='attribute',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='elementdefinition',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='elementdefinition',
            name='element',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='elementdefinition',
            name='type',
            field=models.CharField(choices=[('NONE', 'not any special type'), ('ROLE', 'ARIA Role'), ('PROP', 'ARIA Property'), ('STAT', 'ARIA State'), ('EVNT', 'Event'), ('FONT', 'CSS Font'), ('COLR', 'CSS Color'), ('POS', 'CSS Position'), ('HIGH', 'CSS Highlight'), ('CONT', 'CSS Content')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='elementdefinition',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='elementdefinition',
            name='value',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='languagespec',
            name='element_based',
            field=models.BooleanField(default=True, verbose_name='Element based markup (otherwise property based, i.e. CSS)'),
        ),
    ]
