# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=1024)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[(b'NR', b'No Response'), (b'FB', b'Filed bug'), (b'FFR', b'Filed feature enhancment'), (b'R', b'Responded')], default=b'NR', max_length=128)),
                ('comments', models.TextField(blank=True, default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
