# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=1024)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[(b'All', b'All Users'), (b'New', b'Users who have have joined within last 30 days'), (b'Freq', b'Users who have run more than one report in last 60 days'), (b'Sub', b'Users who have a paid subscription'), (b'Free', b'Users who current account type os free'), (b'Inact', b'Users who have not run a report in more than 120 days')], default=b'All', max_length=8)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
