# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='email',
            field=models.BooleanField(default=True, verbose_name=b'E-mail to users'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[(b'New', b'New Annoucement.'), (b'Sending', b'Announcement is being sent through e-mail.'), (b'Visible', b'Announcement is visiable on selected views.'), (b'Archived', b'Announcement is available in the archive.')], default=b'New', max_length=8),
        ),
        migrations.AddField(
            model_name='announcement',
            name='web',
            field=models.BooleanField(default=True, verbose_name=b'Show in web views'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'End date for showing in web views'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='scope',
            field=models.CharField(choices=[(b'All', b'All Users'), (b'New', b'Users who have have joined within last 30 days'), (b'Sub', b'Users who have a paid subscription'), (b'Free', b"Users who's current account type is Free")], default=b'All', max_length=8),
        ),
    ]
