# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20161006_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='message',
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_html',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_markdown',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='scope',
            field=models.CharField(choices=[(b'All', b'All Users'), (b'Sub', b'Users who have a paid subscription'), (b'Free', b"Users who's current account type is Free")], default=b'All', max_length=8),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[(b'New', b'New Annoucement.'), (b'Sending', b'Announcement is being sent through e-mail.'), (b'Visible', b'Announcement is visible in web views.'), (b'Arch', b'Announcement is only available in the archive.')], default=b'New', max_length=8),
        ),
    ]
