# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20161007_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message_html',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message_markdown',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
