# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20161110_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='email',
            field=models.BooleanField(default=True, verbose_name='E-mail to users'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date for showing in web views'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='scope',
            field=models.CharField(choices=[('All', 'All Users'), ('Sub', 'Users who have a paid subscription'), ('Free', "Users who's current account type is Free")], default='All', max_length=8),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('New', 'New Annoucement.'), ('Sending', 'Announcement is being sent through e-mail.'), ('Visible', 'Announcement is visible in web views.'), ('Arch', 'Announcement is only available in the archive.')], default='New', max_length=8),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='web',
            field=models.BooleanField(default=True, verbose_name='Show in web views'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('NR', 'No Response'), ('FB', 'Filed bug'), ('FFR', 'Filed feature enhancment'), ('R', 'Responded')], default='NR', max_length=128),
        ),
    ]
