#!/usr/bin/env bash

url=$1
if [ -z $url ]
then
    echo "Please specify a URL to inspect..."
    exit
fi

opt=$2

. org/ainspector/util/classpath
java org.ainspector.util.AInspector --filename test/scripts.txt --url $url $opt
