# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20170209_1653'),
        ('pageResults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageresult',
            name='excluded_urls',
            field=models.ManyToManyField(to='reports.ExcludedURL'),
        ),
    ]
