# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageResults', '0002_pageresult_excluded_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageresult',
            name='excluded_urls',
            field=models.ManyToManyField(related_name='page_all_results', to='reports.ExcludedURL'),
        ),
    ]
