# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageResults', '0003_auto_20170226_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageresult',
            name='excluded_urls',
        ),
    ]
