# Generated by Django 2.2.7 on 2019-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageResults', '0004_remove_pageresult_excluded_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageguidelineresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='pageguidelineresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='pageguidelineresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='pageguidelineresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='Page Title'),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='url',
            field=models.URLField(default='', max_length=4096, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='pageresult',
            name='url_encoded',
            field=models.URLField(default='', max_length=8192, verbose_name='Page URL (encoded)'),
        ),
        migrations.AlterField(
            model_name='pagerulecategoryresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='pagerulecategoryresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='pagerulecategoryresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='pagerulecategoryresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='element_results_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='result_message',
            field=models.CharField(default='none', max_length=4096, verbose_name='Rule Result Message'),
        ),
        migrations.AlterField(
            model_name='pageruleresult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='pagerulescoperesult',
            name='implementation_pass_fail_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Pass/Fail Status'),
        ),
        migrations.AlterField(
            model_name='pagerulescoperesult',
            name='implementation_status',
            field=models.CharField(choices=[('U', 'Undefined'), ('NA', 'Not applicable'), ('NI', 'Not Implemented'), ('PI', 'Partial Implementation'), ('AC', 'Almost Complete'), ('NI-MC', 'Not Implemented with manual checks required'), ('PI-MC', 'Partial Implementation with manual checks required'), ('AC-MC', 'Almost Complete with manual checks required'), ('C', 'Complete')], default='U', max_length=8, verbose_name='Implementation Status'),
        ),
        migrations.AlterField(
            model_name='pagerulescoperesult',
            name='manual_check_status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('NA', 'Not Applicable'), ('P', 'Passed'), ('F', 'Fail')], default='NC', max_length=2, verbose_name='Manual Check Status'),
        ),
        migrations.AlterField(
            model_name='pagerulescoperesult',
            name='slug',
            field=models.SlugField(blank=True, default='none', editable=False, max_length=32),
        ),
    ]
