# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_id', models.IntegerField(default=0)),
                ('one_month', models.IntegerField(default=0)),
                ('three_month', models.IntegerField(default=0)),
                ('six_month', models.IntegerField(default=0)),
                ('twelve_month', models.IntegerField(default=0)),
                ('account_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='accounts.AccountType')),
            ],
            options={
                'ordering': ['account_type'],
                'verbose_name': 'Account Type Cost',
                'verbose_name_plural': 'Account Type Costs',
            },
        ),
    ]
