# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
